[package]
name = "advent_of_code"
version = "0.1.0"

[dependencies]
regex = "1.10.2"

[[bin]]
name = "day-01"
path = "day-01/main.rs"

[[bin]]
name = "day-02"
path = "day-02/main.rs"

[[bin]]
name = "day-03"
path = "day-03/main.rs"
